### PR TITLE
Add uniswap v3 and kovan config

### PR DESCRIPTION
**Pull request by mohammadranjbarz**

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
I deployed on https://thegraph.com/explorer/subgraph/mohammadranjbarz/giv-economy-kovan but it would take some time to get synced

**Comment by mohammadranjbarz** [comment]
I tested both staging and new subgraph  with this query
```
{uniswapV3Pool: uniswapV3Pool(
    id: "0x3c2455a3ee0d824941c9329c01a66b86078c3e82"
  ) {
    token0
    token1
    sqrtPriceX96
    tick
    liquidity
  }
  userNotStakedPositions: uniswapPositions(
    where: {
      owner: "0x5f672d71399d8cdba64f596394b4f4381247e025"
      closed: false
    }
  ) {
    tokenId
    token0
    token1
    liquidity
    tickLower
    tickUpper
    staked
    staker
  }
  userStakedPositions: uniswapPositions(
    where: { staker: "0x5f672d71399d8cdba64f596394b4f4381247e025" }
  ) {
    tokenId
    token0
    token1
    liquidity
    tickLower
    tickUpper
    staked
    staker
  }
  allPositions: uniswapPositions(first: 1000, where: { closed: false }) {
    tokenId
    token0
    token1
    liquidity
    tickLower
    tickUpper
    staked
    staker
  }
  infinitePositionRewardInfo: uniswapInfinitePosition(id: 9985) {
    id
    lastRewardAmount
    lastUpdateTimeStamp
  }
  infinitePositionInfo: uniswapPosition(id: 9985) {
    tokenId
    token0
    token1
    liquidity
    tickLower
    tickUpper
    staked
    staker
  }
}
```

Staging result:
```
{
    "data": {
        "uniswapV3Pool": {
            "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
            "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
            "sqrtPriceX96": "202300596239815949505341244",
            "tick": "-119413",
            "liquidity": "1068403359571974898415"
        },
        "userNotStakedPositions": [
            {
                "tokenId": "9234",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "666242761909211718",
                "tickLower": -188640,
                "tickUpper": -24000,
                "staked": false,
                "staker": null
            }
        ],
        "userStakedPositions": [
            {
                "tokenId": "9142",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "1583614855810529",
                "tickLower": -135960,
                "tickUpper": 0,
                "staked": true,
                "staker": "0x5f672d71399d8cdba64f596394b4f4381247e025"
            },
            {
                "tokenId": "9231",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "666242761909211718",
                "tickLower": -188640,
                "tickUpper": -24000,
                "staked": true,
                "staker": "0x5f672d71399d8cdba64f596394b4f4381247e025"
            },
            {
                "tokenId": "9232",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "666242761909211718",
                "tickLower": -188640,
                "tickUpper": -24000,
                "staked": true,
                "staker": "0x5f672d71399d8cdba64f596394b4f4381247e025"
            }
        ],
        "allPositions": [
            {
                "tokenId": "10096",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "828850805400743405232",
                "tickLower": -119700,
                "tickUpper": -119220,
                "staked": false,
                "staker": null
            },
            {
                "tokenId": "10335",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "2559756002459556462",
                "tickLower": -119520,
                "tickUpper": -180,
                "staked": false,
                "staker": null
            },
            {
                "tokenId": "10880",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "131057823843877713500697",
                "tickLower": -119520,
                "tickUpper": -119460,
                "staked": false,
                "staker": null
            },
            {
                "tokenId": "11901",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "165515663416277899058",
                "tickLower": -119460,
                "tickUpper": -119220,
                "staked": false,
                "staker": null
            },
            {
                "tokenId": "9142",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "1583614855810529",
                "tickLower": -135960,
                "tickUpper": 0,
                "staked": true,
                "staker": "0x5f672d71399d8cdba64f596394b4f4381247e025"
            },
            {
                "tokenId": "9153",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "31622235533142758729",
                "tickLower": -713820,
                "tickUpper": 161160,
                "staked": true,
                "staker": "0xed8db37778804a913670d9367aaf4f043aad938b"
            },
            {
                "tokenId": "9177",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "2358763023687465278",
                "tickLower": -129240,
                "tickUpper": -126120,
                "staked": false,
                "staker": null
            },
            {
                "tokenId": "9178",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "2358763023687465278",
                "tickLower": -129240,
                "tickUpper": -126120,
                "staked": false,
                "staker": null
            },
            {
                "tokenId": "9179",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "2076928836144278891",
                "tickLower": -129060,
                "tickUpper": 0,
                "staked": false,
                "staker": null
            },
            {
                "tokenId": "9207",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "15576966271082091696",
                "tickLower": -129060,
                "tickUpper": -128820,
                "staked": false,
                "staker": null
            },
            {
                "tokenId": "9210",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "2076928836144278891",
                "tickLower": -129060,
                "tickUpper": 0,
                "staked": false,
                "staker": null
            },
            {
                "tokenId": "9211",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "2076928836144278891",
                "tickLower": -129060,
                "tickUpper": 0,
                "staked": false,
                "staker": null
            },
            {
                "tokenId": "9231",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "666242761909211718",
                "tickLower": -188640,
                "tickUpper": -24000,
                "staked": true,
                "staker": "0x5f672d71399d8cdba64f596394b4f4381247e025"
            },
            {
                "tokenId": "9232",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "666242761909211718",
                "tickLower": -188640,
                "tickUpper": -24000,
                "staked": true,
                "staker": "0x5f672d71399d8cdba64f596394b4f4381247e025"
            },
            {
                "tokenId": "9234",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "666242761909211718",
                "tickLower": -188640,
                "tickUpper": -24000,
                "staked": false,
                "staker": null
            },
            {
                "tokenId": "9908",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "15811109849675014824",
                "tickLower": -887220,
                "tickUpper": 887220,
                "staked": true,
                "staker": "0x839395e20bbb182fa440d08f850e6c7a8f6f0780"
            },
            {
                "tokenId": "9909",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "15811109849675014824",
                "tickLower": -887220,
                "tickUpper": 887220,
                "staked": false,
                "staker": null
            },
            {
                "tokenId": "9910",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "117938151184374453988",
                "tickLower": -131220,
                "tickUpper": -126120,
                "staked": true,
                "staker": "0x47acab378bf6a67b8a0bd722be323568bdca4203"
            },
            {
                "tokenId": "9985",
                "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
                "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
                "liquidity": "1581110984966930",
                "tickLower": -887220,
                "tickUpper": 887220,
                "staked": false,
                "staker": null
            }
        ],
        "infinitePositionRewardInfo": {
            "id": "9985",
            "lastRewardAmount": "606277121662174590",
            "lastUpdateTimeStamp": "1647877036"
        },
        "infinitePositionInfo": {
            "tokenId": "9985",
            "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
            "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
            "liquidity": "1581110984966930",
            "tickLower": -887220,
            "tickUpper": 887220,
            "staked": false,
            "staker": null
        }
    }
}
```

* new subgraph result
```
{
  "data": {
    "uniswapV3Pool": {
      "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
      "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
      "sqrtPriceX96": "202300596239815949505341244",
      "tick": "-119413",
      "liquidity": "1068403359571974898415"
    },
    "userNotStakedPositions": [
      {
        "tokenId": "9234",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "666242761909211718",
        "tickLower": -188640,
        "tickUpper": -24000,
        "staked": null,
        "staker": null
      }
    ],
    "userStakedPositions": [
      {
        "tokenId": "9142",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "1583614855810529",
        "tickLower": -135960,
        "tickUpper": 0,
        "staked": true,
        "staker": "0x5f672d71399d8cdba64f596394b4f4381247e025"
      },
      {
        "tokenId": "9231",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "666242761909211718",
        "tickLower": -188640,
        "tickUpper": -24000,
        "staked": true,
        "staker": "0x5f672d71399d8cdba64f596394b4f4381247e025"
      },
      {
        "tokenId": "9232",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "666242761909211718",
        "tickLower": -188640,
        "tickUpper": -24000,
        "staked": true,
        "staker": "0x5f672d71399d8cdba64f596394b4f4381247e025"
      }
    ],
    "allPositions": [
      {
        "tokenId": "10096",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "828850805400743405232",
        "tickLower": -119700,
        "tickUpper": -119220,
        "staked": false,
        "staker": null
      },
      {
        "tokenId": "10335",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "2559756002459556462",
        "tickLower": -119520,
        "tickUpper": -180,
        "staked": null,
        "staker": null
      },
      {
        "tokenId": "10880",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "131057823843877713500697",
        "tickLower": -119520,
        "tickUpper": -119460,
        "staked": false,
        "staker": null
      },
      {
        "tokenId": "11901",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "165515663416277899058",
        "tickLower": -119460,
        "tickUpper": -119220,
        "staked": null,
        "staker": null
      },
      {
        "tokenId": "9142",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "1583614855810529",
        "tickLower": -135960,
        "tickUpper": 0,
        "staked": true,
        "staker": "0x5f672d71399d8cdba64f596394b4f4381247e025"
      },
      {
        "tokenId": "9153",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "31622235533142758729",
        "tickLower": -713820,
        "tickUpper": 161160,
        "staked": true,
        "staker": "0xed8db37778804a913670d9367aaf4f043aad938b"
      },
      {
        "tokenId": "9177",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "2358763023687465278",
        "tickLower": -129240,
        "tickUpper": -126120,
        "staked": false,
        "staker": null
      },
      {
        "tokenId": "9178",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "2358763023687465278",
        "tickLower": -129240,
        "tickUpper": -126120,
        "staked": false,
        "staker": null
      },
      {
        "tokenId": "9179",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "2076928836144278891",
        "tickLower": -129060,
        "tickUpper": 0,
        "staked": false,
        "staker": null
      },
      {
        "tokenId": "9207",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "15576966271082091696",
        "tickLower": -129060,
        "tickUpper": -128820,
        "staked": null,
        "staker": null
      },
      {
        "tokenId": "9210",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "2076928836144278891",
        "tickLower": -129060,
        "tickUpper": 0,
        "staked": false,
        "staker": null
      },
      {
        "tokenId": "9211",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "2076928836144278891",
        "tickLower": -129060,
        "tickUpper": 0,
        "staked": false,
        "staker": null
      },
      {
        "tokenId": "9231",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "666242761909211718",
        "tickLower": -188640,
        "tickUpper": -24000,
        "staked": true,
        "staker": "0x5f672d71399d8cdba64f596394b4f4381247e025"
      },
      {
        "tokenId": "9232",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "666242761909211718",
        "tickLower": -188640,
        "tickUpper": -24000,
        "staked": true,
        "staker": "0x5f672d71399d8cdba64f596394b4f4381247e025"
      },
      {
        "tokenId": "9234",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "666242761909211718",
        "tickLower": -188640,
        "tickUpper": -24000,
        "staked": null,
        "staker": null
      },
      {
        "tokenId": "9908",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "15811109849675014824",
        "tickLower": -887220,
        "tickUpper": 887220,
        "staked": true,
        "staker": "0x839395e20bbb182fa440d08f850e6c7a8f6f0780"
      },
      {
        "tokenId": "9909",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "15811109849675014824",
        "tickLower": -887220,
        "tickUpper": 887220,
        "staked": null,
        "staker": null
      },
      {
        "tokenId": "9910",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "117938151184374453988",
        "tickLower": -131220,
        "tickUpper": -126120,
        "staked": true,
        "staker": "0x47acab378bf6a67b8a0bd722be323568bdca4203"
      },
      {
        "tokenId": "9985",
        "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
        "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
        "liquidity": "1581110984966930",
        "tickLower": -887220,
        "tickUpper": 887220,
        "staked": false,
        "staker": null
      }
    ],
    "infinitePositionRewardInfo": {
      "id": "9985",
      "lastRewardAmount": "606277121662174590",
      "lastUpdateTimeStamp": "1647877036"
    },
    "infinitePositionInfo": {
      "tokenId": "9985",
      "token0": "0x29434a25abd94ae882aa883eea81585aaa5b078d",
      "token1": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
      "liquidity": "1581110984966930",
      "tickLower": -887220,
      "tickUpper": 887220,
      "staked": false,
      "staker": null
    }
  }
}
```

**Comment by mohammadranjbarz** [comment]
@aminlatifi  I checked both result and they are same, so it seems functionality is ok, if code quality was ok you can merge it.

**Comment by aminlatifi** [comment]
Thanks @mohammadranjbarz 
LGTM

**Pull request merged**
